### ISSUE TITLE
A webhook to centralize showoff posts!

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#112]
It would be awesome if we could hook into the current showoff system, perhaps even through the analytics system, and send posts that happen to a webhook that could then be captured in discord, such that the headquarters server has a live feed of people's posts, the projects they post to, etc.

I think that'd be super cool, just a giant stream of showoff work. It would be especially awesome during the game jam, and even cooler if people's scholastic association came up. If we can have such a webhook ready to flow before the Friday kickoff, I could demonstrate the bot in the kickoff presentation and invite everyone to generate a project on our site!

Marking as high prio due to the time value of the idea (best before game jam, but admittedly just a feature)

**Comment by Exanite** [comment]
This should just involve creating an event handler on the backend and adding the webhook url to the backend config.

**Comment by Exanite** [comment]
Formatting the content might be more tricky.

**Comment by Exanite** [comment]
~~Todo:~~
~~- [ ] Bot profile pic~~
~~- [ ] Link to user profile on website~~
~~- [ ] Link to associated project on website~~
