### ISSUE TITLE
Cleaner showoff channels with ephemeral [opinion]

### ISSUE THREAD

**Issue by CoderJoshDK** [UF-GDA/Feedback#120]
## **Is your feature request related to a problem? Please describe.**
Cleaning up the feel of "showoff" in servers

## **Describe the solution you'd like**
The message the bot sends doesn't need to be public/shown/permanent. Making the response ephemeral should clean it up. This is another design choice up to you guys. But, it feels cleaner this way in my mind.  

## **Describe alternatives you've considered**
The information can be displayed like how MEE6 does it. When someone wants to know what their stats are, there is a command that shows it (this is something you already have)
If you want people to know when someone has reached a milestone (maybe like the equivalent of leveling up for your streaks ie a specific amount of points have been earned. ) you can still post that. But there is no need to display every time some uploads a showoff. 

## **Additional context**
Personally feel like this clutters up the channel. 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/74162303/201999238-b672ad75-8270-48c8-a638-dc220f1329a0.png">

For milestones, you could do something like this :  
<img width="424" alt="image" src="https://user-images.githubusercontent.com/74162303/201999177-6f9d52b0-2b69-4aec-98a0-29740ec4fcdf.png"> if you still wanted to show to let people know that a user is really posting out a ton of stuff!

This is another instance of me sticking my nose into your personal design choices; meaning, you can go with what you think is right and I won't be offended in any manner.  
Happy developing 👍

**Comment by Exanite** [comment]
While the content of the message can be changed, I don't think we will be removing the message completely.

Without the message, the bot's impact on the channel essentially drops to zero. If no one knows the bot exists, no one will use it. Additionally, part of the showoff channel's purpose is to track points and streaks as an incentive to work on game dev every day. Ideally, the message incentivizes other people to show off their work as well. Making the point/streak information be hidden in a separate command hinders this. Another thing to note is that the message is helpful for moderation or reminding people that they forgot to upload.

**Comment by CoderJoshDK** [comment]
Very fair   

I am just saying this next point as an idea; you can have the message display but set it to delete after a few hours or even a day. I know that the library I use makes this really easy to do, not sure about the language you do. If too complicated, definitely not worth making a db entry to solve. But I do understand your point about getting the bot in peoples' faces so they use it.

**Comment by Exanite** [comment]
We've implemented this in addition to adding a role awarded message and star reaction on the showed off message.
![image](https://user-images.githubusercontent.com/42710136/211171757-7f71a332-e329-4712-b911-18f28c192650.png)
