### ISSUE TITLE
Showoff command error when attempting to submit without Project or Tags filled

### ISSUE THREAD

**Issue by Exanite** [UF-GDA/Feedback#16]
**Bug Report from user**
Attempting to submit showoff post w/o either project name or tag causes "Please try again message" Upon fixing the missing information and trying again, user gets "Interaction Failed. Try Again" and can't submit unless they quite out that ethereal message and try to showoff again. Essentially, failing to submit correctly the first time prevents the user from submitting at all until they restart the showoff process

**Comment by Skunkmeister** [comment]
Solved. onSenditButton() was triggering a pop on the stack holding the bot states, regardless of success. Made it into a boolean function > void, checked for successful return, responded accordingly.
