### ISSUE TITLE
Showoff command incorrectly caches messages

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#169]
**Description**
Bot responds to showoff command differently inside of showoff vs outside.

**To Reproduce**
1. Attempt to show off a post using typed /showoff command or right click > showoff.
In showoff-designated channels, short descriptions are not caught. Outside showoff channels, short description will be caught.

**Expected behavior**
Consistent catching of short descriptions independent of channel.

**Additional context**
[Related discussion and discovery in HQ Discord.](https://discord.com/channels/521957275204845578/1067880168561049671/1168262894253772811)

**Comment by Exanite** [comment]
This seems to be incorrect. 

The actual cause seems to be that slash command version of /showoff caches the originally shown off message.
