### ISSUE TITLE
Storage of bot data and configuration

### ISSUE THREAD

**Issue by Exanite** [UF-GDA/Feedback#56]
Per server setup of welcome message, showoff channel to respect, and anything else we can think of down the line in addition to ensuring user interactions are exclusively from an approved discord (anyone can add the bot but not everyone should be able to use it)

**Comment by ModeratelyGreek** [comment]
Per server setup of welcome message, showoff channel to respect, and anything else we can think of down the line in addition to ensuring user interactions are exclusively from an approved discord (anyone can add the bot but not everyone should be able to use it)

**Comment by Exanite** [comment]
Since this data doesn't contain any secrets, it would be easier to hardcode all of these values in the source code first and then set up an api to update these from the backend.

A lot of values will probably be nullable as well since these will have to be set up per discord server.
