### ISSUE TITLE
Fix Overflow Issues on Homepage

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#61]
Safari isn't horizontal scroll-locking the site, allowing me to go past the rightmost bounds of the window. Additionally, threeJs overflows on smaller aspect ratios. Need to adjust!

- [X] 3d render overflow
- [x] Safari project showcase overflow
- [x] Double check for other places with overflowing content on Safari

![image](https://user-images.githubusercontent.com/42710136/184652116-d56325de-60be-457a-98f1-9739bd16b934.png)

From https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=www.google.com&speed=1
![image](https://user-images.githubusercontent.com/42710136/184652664-53e708e1-c829-4180-b04c-15f648eb4b6d.png)
![image](https://user-images.githubusercontent.com/42710136/184652674-d5094350-aecd-43cf-a3c4-a72539605f89.png)

**Comment by Exanite** [comment]
Overflowing on smaller screen sizes has been fixed.

Can you confirm if the Safari issues still exist in the latest dev version of the website?
