### ISSUE TITLE
Markdown list spacing misbehaves

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#63]
Spacing appears in nested list as a function of the spacing in the prior parent bullet. See gif for clarification
![chrome_gDQ18TxN7h](https://user-images.githubusercontent.com/4400062/183229441-a5d01d84-8ef6-42fe-89cb-a9fe43adff97.gif)
:

**Comment by Exanite** [comment]
### Main case

Far - Close

- Test

- Test
    - Test
    - Test
    - Test
    
---

Close - Close

- Test
- Test
    - Test
    - Test
    - Test

---

Far - Far

- Test

- Test
    - Test
    
    - Test
    
    - Test
    
---

Close - Far

- Test
- Test
    - Test
    
    - Test
    
    - Test

### Other cases

- Test
- Test
- Test

---

1. Test
1. Test
1. Test

---

- Test

- Test

- Test

---

1. Test

1. Test

1. Test

---

- Test
- Test
- Test
  - Test
  - Test
  - Test

---

1. Test
1. Test
1. Test
    1. Test
    1. Test
    1. Test

---

- Test

- Test

- Test
    - Test
    - Test
    - Test

---

1. Test

1. Test

1. Test
    1. Test
    1. Test
    1. Test

**Comment by Exanite** [comment]
Regarding website renderer:
No \<p> element in `Close - Any` cases, causing the lobotomized owl selector to not affect the nested list.
![image](https://user-images.githubusercontent.com/42710136/183536370-b618c849-cd63-4866-91c1-d6e2cfd70c40.png)

**Comment by Exanite** [comment]
Interestingly, the Github markdown renderer outputs the same html elements.
