### ISSUE TITLE
Optimize home page 3d model

### ISSUE THREAD

**Issue by Exanite** [UF-GDA/Feedback#65]
Currently causes 100% GPU utilization and makes the home page completely unusable for me since I'm using a 4k monitor, but also keep in mind that there are computers without GPUs out there and we should also test on those if possible.

**Comment by ModeratelyGreek** [comment]
Need to rewrite bloom shader. Most performant option is box gaussian / fast gaussian. Costs a few mb of VRAM at the return of 48x performance or so compared to current "quality" settings.
