### ISSUE TITLE
Add a very obvious invitation to our discord front-and-center on our website

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#69]
Discord is our true hub for the time being. Website is lovely but needs to efficiently direct prospective members to discord once its SEO'd well.

**Comment by ModeratelyGreek** [comment]
Alright, going to quickly get to this as a warm-up before I start "improving home page accessibility"

**Comment by Skunkmeister** [comment]
test test

**Comment by ModeratelyGreek** [comment]
Ok this has turned into a UI design adventure over on penpot
