### ISSUE TITLE
Add everyone's points back from old showoff

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#80]
I need to go in and manually add in points where possible to former users who run bot accounts, now that the 105 days season is over.

**Comment by Exanite** [comment]
Any thoughts on how we should handle users that do not have DevLUp accounts?

**Comment by ModeratelyGreek** [comment]
I think I will message them all / ping them all...
That way they make an account.

**Comment by ModeratelyGreek** [comment]
Ones who dont should be ignored...

**Comment by ModeratelyGreek** [comment]
In retrospect I don't think this is worth it. Many newcomers have come, old people have left, etc. We can move on from this one...
