### ISSUE TITLE
Zooming out on Home page should not affect 3d renderer resolution

### ISSUE THREAD

**Issue by Exanite** [UF-GDA/Feedback#82]
Haven't confirmed if it actually is the resolution, but the renderer becomes extremely laggy when zooming out

**Comment by Exanite** [comment]
Zooming in appears to have the opposite effect
![image](https://user-images.githubusercontent.com/42710136/184813769-fe284319-1c41-4d36-adb5-005037f4eae4.png)

**Comment by ModeratelyGreek** [comment]
That is super strange. There's a lot of redundancy and noticeable inconsistency in Drei/post processing when it comes to propagating sizing updates down to the components involved in composing shaders. I'll take a look at this.

**Comment by Exanite** [comment]
Fixed by using `window.devicePixelRatio` and detecting when `window.devicePixelRatio` changes (https://stackoverflow.com/questions/28905420/window-devicepixelratio-change-listener).
